apiVersion: v1
kind: Service
metadata:
  name: nodejs-website-test
spec:
  selector:
    app: nodejs-website-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
